source: public/ 
region: eu-north-1
bucket: staticbattery.com 
acl: public-read 
distribution-id: E15NLNM65B1T1F 

routes:
    - route: "^.+\\.(js|css|svg|ttf)$"
      #  cache static assets for 20 years
      headers:
         Cache-Control: "max-age=630720000, no-transform, public"
      gzip: true
    - route: "^.+\\.(png|jpg|webp)$"
      headers:
         Cache-Control: "max-age=630720000, no-transform, public"
      gzip: true
    - route: "^.+\\.(html|xml)$"
      gzip: true
    - route: "^.+\\.(json)$"
      gzip: true
      headers:
        # 1 day.
         Cache-Control: "max-age=86400, no-transform, public"
      
        